import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createRuntime,folder} from './runtime.mjs';

const runtime=await createRuntime({mock:true});
const results=[];
const sockets=[];
function passed(name){results.push({name,pass:true});console.log('PASS '+name);}
const api=(path,options={})=>runtime.api.fetch('http://127.0.0.1:8787'+path,{redirect:'manual',...options});
const live=(path,options={})=>runtime.live.fetch('http://127.0.0.1:8788'+path,{redirect:'manual',...options});
const post=(token,body)=>({method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});
try {
  assert.equal((await api('/api/v1/health')).status,200);
  assert.equal((await live('/health')).status,200);passed('two Worker health routes');
  assert.equal((await api('/api/v2/auth/me')).status,401);passed('unauthenticated account rejected');
  const start=await api('/api/v2/auth/discord/start?returnTo=/dashboard/');
  assert.equal(start.status,302);
  const oauth=new URL(start.headers.get('location'));
  assert.equal(oauth.searchParams.get('scope'),'identify');
  assert.equal(oauth.searchParams.get('redirect_uri'),'http://127.0.0.1:8787/api/v2/auth/discord/callback');
  const setCookies=start.headers.getSetCookie();
  assert(setCookies.every(c=>c.includes('HttpOnly')&&c.includes('Secure')&&c.includes('SameSite=Lax')&&c.includes('Max-Age=600')));
  const cookie=setCookies.map(c=>c.split(';')[0]).join('; ');
  assert.equal((await api('/api/v2/auth/discord/callback?code=mock&state=wrong',{headers:{cookie}})).status,400);passed('OAuth scope, callback and state protection');
  const callback=await api('/api/v2/auth/discord/callback?code=mock&state='+encodeURIComponent(oauth.searchParams.get('state')),{headers:{cookie}});
  assert.equal(callback.status,302);
  const exchangeCode=new URL(callback.headers.get('location')).searchParams.get('veyra_auth');
  const exchange=await api('/api/v2/auth/exchange',post(null,{code:exchangeCode}));
  assert.equal(exchange.status,200);
  const session=await exchange.json();
  assert.equal(session.user.username,'testuser');
  assert.equal((await api('/api/v2/auth/exchange',post(null,{code:exchangeCode}))).status,401);
  const headers={authorization:'Bearer '+session.token};
  assert.equal((await api('/api/v2/auth/me',{headers})).status,200);passed('mock Discord login and single-use exchange');
  const generated=await api('/api/v2/dashboard-key/generate',post(session.token,{}));
  assert.equal(generated.status,200);
  const {dashboardKey}=await generated.json();
  assert(dashboardKey);
  assert.equal((await api('/api/v2/dashboard-key/generate',post(session.token,{}))).status,409);passed('key generation and replacement confirmation');
  const snapshot={schemaVersion:1,type:'snapshot',player:{userId:900002,name:'robloxuser',displayName:'robloxuser'},session:{id:'aroyn-local-integration-900002'},product:{version:'test'},cash:2400000};
  assert.equal((await api('/api/v2/runtime/link',post(dashboardKey,{robloxUserId:'900002'}))).status,200);
  assert.equal((await api('/api/v2/runtime/push',post(dashboardKey,snapshot))).status,200);
  const accounts=await (await api('/api/v2/runtime/accounts',{headers})).json();
  assert.equal(accounts.accounts[0].userId,'900002');
  const stored=await (await api('/api/v2/runtime/snapshot?robloxUserId=900002',{headers})).json();
  assert.equal(stored.snapshot.player.name,'robloxuser');passed('account linking and R2 snapshot round trip');
  const runtimeToken=await live('/token',post(dashboardKey,{robloxUserId:'900002'}));
  assert.equal(runtimeToken.status,200);
  const rt=await runtimeToken.json();
  const webToken=await live('/web-token',post(session.token,{robloxUserId:'900002'}));
  assert.equal(webToken.status,200);
  const wt=await webToken.json();
  assert.equal((await live('/web-token',post(session.token,{robloxUserId:'900003'}))).status,403);
  assert.equal((await live('/ws?token=invalid',{headers:{Upgrade:'websocket'}})).status,401);passed('shared D1 identity and WebSocket token authorization');
  const dashboardResponse=await live('/ws?token='+encodeURIComponent(wt.token),{headers:{Upgrade:'websocket'}});
  assert.equal(dashboardResponse.status,101);
  const dashboardSocket=dashboardResponse.webSocket;
  dashboardSocket.accept();sockets.push(dashboardSocket);
  const runtimeResponse=await live('/ws?token='+encodeURIComponent(rt.token),{headers:{Upgrade:'websocket'}});
  assert.equal(runtimeResponse.status,101);
  const runtimeSocket=runtimeResponse.webSocket;
  runtimeSocket.accept();sockets.push(runtimeSocket);
  const message=new Promise((resolveMessage,reject)=>{
    const timer=setTimeout(()=>reject(new Error('Snapshot relay timed out')),5000);
    dashboardSocket.addEventListener('message',event=>{let data;try{data=JSON.parse(event.data);}catch{return;}if(data.type==='snapshot'&&data.player?.name==='robloxuser'){clearTimeout(timer);resolveMessage(data);}});
  });
  runtimeSocket.send(JSON.stringify(snapshot));await message;passed('live runtime-to-dashboard WebSocket relay');
  assert.equal((await api('/api/v2/auth/logout',{method:'POST',headers})).status,200);
  assert.equal((await api('/api/v2/auth/me',{headers})).status,401);
  assert.equal((await live('/web-token',post(session.token,{robloxUserId:'900002'}))).status,401);passed('logout revokes the shared web session');
  await writeFile(resolve(folder,'check-results.json'),JSON.stringify({externalServices:'mocked; no real Discord or Roblox login',results},null,2)+'\n');
} finally {for(const socket of sockets)try{socket.close(1000,'Local test finished');}catch{}await runtime.mf.dispose();}
